<?php
/**
 * TodolistApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Todolist RESTful API
 *
 * OpenAPI for Todolist RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: ikoafianando123@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.30
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TodolistApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TodolistApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for todolistGet
     *
     * Get All Todolist.
     *
     */
    public function testTodolistGet()
    {
    }

    /**
     * Test case for todolistPost
     *
     * Create New Todolist.
     *
     */
    public function testTodolistPost()
    {
    }

    /**
     * Test case for todollistTodolistIdDelete
     *
     * Delete existing Todolist.
     *
     */
    public function testTodollistTodolistIdDelete()
    {
    }

    /**
     * Test case for todollistTodolistIdPut
     *
     * Update existing Todolist.
     *
     */
    public function testTodollistTodolistIdPut()
    {
    }
}
